# Generated by Django 4.1.3 on 2022-11-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
