# Generated by Django 4.1.3 on 2022-11-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='username',
        ),
    ]
