# Generated by Django 4.1.3 on 2022-11-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, unique=True)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(default='', max_length=200, unique=True)),
                ('about_me', models.CharField(default='', max_length=200)),
                ('career_objective', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
